/*
 * Generated by MTK Easy PinMux Tool Version 2.3.1 for 7686D. Copyright MediaTek Inc. (C) 2015.
 * 2018-07-06 14:45:18:0483
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
