/*
 * Generated by MTK Easy PinMux Tool Version 2.1.0 for 7686D. Copyright MediaTek Inc. (C) 2015.
 * 2018-06-28 14:45:12:0255
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
